export enum EVENTS {
    AUTHENTICATED = "AUTHENTICATED",
    LOAD_PLAYLISTS = "LOAD_PLAYLISTS",
    REQUEST_PLAYLISTS = "REQUEST_PLAYLISTS",
    APP_READY = "APP_READY",
    QUIT = "QUIT",
    OPEN_AUTHENTICATE_URL = "OPEN_AUTHENTICATE_URL"
}